version: "3.4"

# networks:
#   shared-network:
#     driver: bridge
services:
    pgAdmin:
        restart: always
        image: dpage/pgadmin4
        ports:
            - "8081:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: user@domain.local
            PGADMIN_DEFAULT_PASSWORD: SuperSecret
        depends_on:
          - "postgres"
    postgres:
        restart: always
        image: postgres
        container_name: "postgres_container"
        ports:
            - "5433:5432"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shopping
        volumes:
           - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    app:
      # image: "api-shopping"
        # restart: always
        # pid: "host"
        # networks:
        #   - shared-network
        # hostname: "host"
        # ipc: host
      build: 
          context: .
          dockerfile: ./Dockerfile
        # volumes:
        #   - .:/go/src/app
      ports:
        - "8083:8080"
        # # command: ["go", "run", "cmd/main.go"]